import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { build } from "esbuild";

const outfile = resolve(process.cwd(), "api/_generated/app.js");

await mkdir(dirname(outfile), { recursive: true });

await build({
  entryPoints: [resolve(process.cwd(), "src/app.ts")],
  outfile,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  sourcemap: false,
  banner: {
    js: "// Generated by scripts/build-vercel.ts. Do not edit manually.",
  },
});

await writeFile(
  resolve(process.cwd(), "api/_generated/app.d.ts"),
  'import type { Hono } from "hono";\ndeclare const app: Hono;\nexport default app;\n',
  "utf-8",
);
