const SITE_TITLE = "抖音视频解析";
const SITE_SUBTITLE = "粘贴分享链接，自动解析、预览并下载无水印视频";

export function renderHomePage(): string {
  return String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
  <meta name="theme-color" content="#030303" />
  <title>${SITE_TITLE}</title>
  <style>
    :root{color-scheme:dark;--bg:#030303;--panel:#111113;--soft:#19191c;--line:rgba(255,255,255,.08);--text:#f7f7f8;--muted:rgba(255,255,255,.58);--cyan:#25f4ee;--pink:#fe2c55;--green:#63f59b;--radius:22px;--shadow:0 24px 70px rgba(0,0,0,.42)}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:linear-gradient(135deg,rgba(37,244,238,.08),transparent 28%),linear-gradient(225deg,rgba(254,44,85,.10),transparent 28%),var(--bg);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;color:var(--text);overflow-x:hidden}button,input,textarea{font:inherit}p{margin:0}
    .page{width:min(1180px,100%);margin:0 auto;padding:34px 22px 48px}.header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:24px}.brand{display:flex;gap:12px;align-items:center}.logo{width:44px;height:44px;border-radius:14px;background:linear-gradient(135deg,var(--cyan),var(--pink));display:grid;place-items:center;font-size:24px;font-weight:900;box-shadow:5px 0 0 rgba(254,44,85,.45),-5px 0 0 rgba(37,244,238,.36)}h1{margin:0;font-size:26px;letter-spacing:.02em}.subtitle{margin-top:5px;color:var(--muted);font-size:14px}.badge{border:1px solid var(--line);background:rgba(255,255,255,.05);border-radius:999px;color:var(--muted);padding:9px 13px;font-size:13px;white-space:nowrap;display:flex;align-items:center;gap:8px}.badge b{color:#fff}.online-dot{display:inline-block;width:7px;height:7px;border-radius:99px;background:var(--green);box-shadow:0 0 14px var(--green)}
    .layout{display:grid;grid-template-columns:320px minmax(320px,430px) 320px;gap:18px;align-items:start}.card{background:rgba(17,17,19,.82);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);backdrop-filter:blur(14px)}.pad{padding:18px}.card h2{font-size:16px;margin:0 0 14px}.input{width:100%;min-height:128px;resize:vertical;border:1px solid var(--line);border-radius:18px;background:#070708;color:#fff;padding:15px;line-height:1.55;outline:0}.input:focus,.small-input:focus{border-color:rgba(37,244,238,.75)}.small-input{width:100%;height:43px;border:1px solid var(--line);border-radius:999px;background:#070708;color:#fff;padding:0 14px;outline:0}.btn{border:0;border-radius:999px;min-height:43px;padding:0 16px;background:rgba(255,255,255,.10);color:#fff;font-weight:800;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}.btn:hover{transform:translateY(-1px)}.btn:disabled{opacity:.45;cursor:not-allowed;transform:none}.btn-primary{background:linear-gradient(135deg,var(--cyan),var(--pink));color:#fff}.btn-wide{width:100%;margin-top:12px}.btn-row{display:flex;gap:10px;margin-top:10px}.btn-row .btn{flex:1}.toggle{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:13px;margin-top:12px}.toggle input{accent-color:var(--pink)}.status{min-height:21px;margin-top:12px;color:var(--muted);font-size:13px}.status.ok{color:var(--green)}.status.err{color:var(--pink)}
    .center{display:grid;gap:16px}.phone{position:relative;aspect-ratio:9/16;border-radius:32px;overflow:hidden;background:#000;border:1px solid rgba(255,255,255,.10);box-shadow:0 0 0 8px rgba(255,255,255,.035),var(--shadow)}video{width:100%;height:100%;object-fit:contain;background:#000}.empty{position:absolute;inset:0;display:grid;place-items:center;text-align:center;padding:36px;background:radial-gradient(circle at 50% 24%,rgba(254,44,85,.12),transparent 40%),#050506}.empty.hidden{display:none}.empty strong{display:block;font-size:27px;text-shadow:4px 0 0 rgba(254,44,85,.50),-4px 0 0 rgba(37,244,238,.38);margin-bottom:10px}.empty span{display:block;color:var(--muted);line-height:1.65}.caption{background:rgba(17,17,19,.82);border:1px solid var(--line);border-radius:18px;padding:14px 16px;backdrop-filter:blur(12px);box-shadow:var(--shadow)}.video-title{font-weight:800;line-height:1.45}.video-author{font-size:13px;color:var(--muted);margin-top:6px}
    .stats{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.stat{background:#08080a;border:1px solid var(--line);border-radius:16px;padding:13px}.stat b{font-size:18px}.stat span{display:block;color:var(--muted);font-size:12px;margin-top:4px}.meta{display:grid;gap:10px;margin-top:12px}.meta-item{background:#0b0b0d;border:1px solid var(--line);border-radius:16px;padding:12px}.meta-item small{display:block;color:var(--muted);margin-bottom:6px}.cover{width:100%;max-height:170px;object-fit:cover;border-radius:16px;border:1px solid var(--line)}.mono{font-family:Consolas,"SFMono-Regular",monospace;font-size:12px;word-break:break-all;color:rgba(255,255,255,.68)}.pill{font-size:12px;border-radius:999px;padding:5px 9px;background:rgba(255,255,255,.08);color:var(--muted)}.pill.success{background:var(--green);color:#07120c}.hidden{display:none!important}
    details{margin-top:14px;border-top:1px solid var(--line);padding-top:14px}summary{cursor:pointer;color:#fff;font-weight:800}.hint{color:var(--muted);font-size:13px;line-height:1.6}.batch-grid{display:grid;gap:10px;margin-top:12px}.batch-row{display:grid;grid-template-columns:1fr 70px 70px;gap:8px}.batch-list{display:grid;gap:10px;max-height:340px;overflow:auto}.batch-item{display:grid;grid-template-columns:46px 1fr auto;gap:10px;align-items:center;background:#09090b;border:1px solid var(--line);border-radius:15px;padding:9px}.thumb{width:46px;height:60px;object-fit:cover;border-radius:10px;background:#111}@media(max-width:1060px){.layout{grid-template-columns:1fr;max-width:520px;margin:0 auto}.header{align-items:flex-start;flex-direction:column}.badge{white-space:normal}.phone{max-height:78vh}}@media(max-width:720px){.page{padding:18px 12px 28px}.header{gap:12px;margin-bottom:14px}.brand{align-items:flex-start}.logo{width:40px;height:40px;flex:0 0 auto;font-size:22px}h1{font-size:22px}.subtitle{font-size:12px;line-height:1.5}.badge{width:100%;justify-content:space-between;padding:9px 11px;font-size:12px}.layout{gap:14px;max-width:100%}.card{border-radius:20px}.pad{padding:14px}.input{min-height:108px;border-radius:16px;font-size:14px}.btn{min-height:48px}.btn-row{display:grid;grid-template-columns:1fr 82px}.center{gap:12px}.phone{width:100%;max-width:420px;margin:0 auto;border-radius:28px;box-shadow:0 0 0 5px rgba(255,255,255,.035),var(--shadow)}.caption{padding:12px 13px;font-size:14px}.video-title{font-size:15px}.video-author{font-size:12px}.stats{grid-template-columns:repeat(4,1fr);gap:6px}.stat{padding:10px 7px;border-radius:14px}.stat b{font-size:15px}.stat span{font-size:11px}.meta{gap:8px}.meta-item{padding:10px;border-radius:14px}.mono{max-height:76px;overflow:auto}.cover{max-height:145px}.batch-row{grid-template-columns:1fr 64px 64px}}
  </style>
</head>
<body>
  <main class="page">
    <header class="header">
      <div class="brand"><div class="logo">♪</div><div><h1>${SITE_TITLE}</h1><p class="subtitle">${SITE_SUBTITLE}</p></div></div>
      <div class="badge"><span>单条免费</span><span>批量需激活</span><span><i class="online-dot"></i> 在线 <b id="onlineCount">--</b></span></div>
    </header>

    <section class="layout">
      <aside class="card pad">
        <h2>粘贴分享链接</h2>
        <textarea id="linkInput" class="input" placeholder="把抖音分享文本或链接粘贴到这里，例如：https://v.douyin.com/xxxx/"></textarea>
        <button id="parseBtn" class="btn btn-primary btn-wide">立即解析</button>
        <div class="btn-row"><button id="clipboardBtn" class="btn" type="button">启用剪贴板识别</button><button id="clearBtn" class="btn" type="button">清空</button></div>
        <label class="toggle"><input id="autoDownload" type="checkbox" checked /> 解析成功后自动下载视频</label>
        <div id="status" class="status">等待链接输入。</div>

        <details>
          <summary>会员批量解析</summary>
          <div class="batch-grid">
            <p class="hint">批量主页解析和批量下载需先激活；单条视频解析不用激活。</p>
            <div style="display:flex;gap:8px"><input id="vipCode" class="small-input" style="flex:1" placeholder="输入激活码" /><button id="vipBtn" class="btn btn-primary" type="button">激活</button></div>
            <span id="vipState" class="pill">未激活</span>
            <input id="profileInput" class="small-input" placeholder="主页链接：https://www.douyin.com/user/..." />
            <div class="batch-row"><button id="inspectBtn" class="btn" type="button">获取数量</button><input id="batchCount" class="small-input" type="number" min="1" value="5" /><input id="batchConcurrency" class="small-input" type="number" min="1" max="5" value="3" /></div>
            <button id="startBatchBtn" class="btn btn-primary" type="button">开始批量解析</button>
            <div id="batchStatus" class="status">激活会员后可用。</div>
          </div>
        </details>
      </aside>

      <section class="center">
        <section class="phone">
          <video id="video" controls playsinline preload="metadata"></video>
          <div id="empty" class="empty"><div><strong>复制即解析</strong><span>识别到抖音视频链接后，会在这里生成预览和下载地址。</span></div></div>
        </section>
        <div class="caption"><div id="videoTitle" class="video-title">还没有解析内容</div><div id="videoAuthor" class="video-author">标题、介绍、音乐和封面会自动展示</div></div>
      </section>

      <aside class="card pad">
        <h2>作品信息 <span id="mediaType" class="pill">待解析</span></h2>
        <div class="stats"><div class="stat"><b id="digg">--</b><span>点赞</span></div><div class="stat"><b id="comment">--</b><span>评论</span></div><div class="stat"><b id="share">--</b><span>转发</span></div><div class="stat"><b id="collect">--</b><span>收藏</span></div></div>
        <div class="meta"><img id="cover" class="cover hidden" alt="视频封面" /><div class="meta-item"><small>标题 / 介绍</small><div id="desc">--</div></div><div class="meta-item"><small>背景音乐</small><div id="music">--</div></div><div class="meta-item"><small>下载地址</small><div id="downloadUrl" class="mono">--</div></div></div>
        <a id="downloadBtn" class="btn btn-primary btn-wide" href="#" download>下载视频</a>
        <details><summary>批量结果</summary><div id="batchSummary" class="status">0/0</div><div id="batchList" class="batch-list"><p class="hint">批量解析结果会显示在这里。</p></div></details>
      </aside>
    </section>
  </main>

  <script>
    const $ = (id) => document.getElementById(id);
    const state = { lastUrl: "", lastDownloaded: "", clipboardWatch: false, vipToken: localStorage.getItem("vip_token") || "", pollTimer: 0 };
    const els = { input:$("linkInput"), parseBtn:$("parseBtn"), clipboardBtn:$("clipboardBtn"), clearBtn:$("clearBtn"), autoDownload:$("autoDownload"), status:$("status"), video:$("video"), empty:$("empty"), videoTitle:$("videoTitle"), videoAuthor:$("videoAuthor"), mediaType:$("mediaType"), digg:$("digg"), comment:$("comment"), share:$("share"), collect:$("collect"), desc:$("desc"), music:$("music"), cover:$("cover"), downloadUrl:$("downloadUrl"), downloadBtn:$("downloadBtn"), onlineCount:$("onlineCount"), vipCode:$("vipCode"), vipBtn:$("vipBtn"), vipState:$("vipState"), profileInput:$("profileInput"), inspectBtn:$("inspectBtn"), batchCount:$("batchCount"), batchConcurrency:$("batchConcurrency"), startBatchBtn:$("startBatchBtn"), batchStatus:$("batchStatus"), batchList:$("batchList"), batchSummary:$("batchSummary") };
    function extractDouyinUrl(text){ const m=String(text||"").match(/https?:\/\/[^\s"'<>，。！？；、]+/i); if(!m)return""; try{const u=new URL(m[0]);const h=u.hostname.toLowerCase();return (h.endsWith("douyin.com")||h.endsWith("iesdouyin.com")||h.endsWith("amemv.com"))?u.toString():"";}catch{return"";} }
    function fmt(n){ return n===null||n===undefined?"--":Number(n).toLocaleString("zh-CN"); }
    function setStatus(el,msg,type){ el.textContent=msg; el.className="status"+(type?" "+type:""); }
    function debounce(fn,ms){ let t; return function(){ clearTimeout(t); const a=arguments; t=setTimeout(function(){ fn.apply(null,a); },ms); }; }
    async function api(path, options){ options=options||{}; const headers=new Headers(options.headers||{}); if(options.body&&!headers.has("content-type"))headers.set("content-type","application/json"); if(state.vipToken)headers.set("authorization","Bearer "+state.vipToken); const res=await fetch(path,Object.assign({},options,{headers})); const json=await res.json().catch(function(){return null;}); if(!res.ok||!json||json.ok===false)throw new Error((json&&json.error&&json.error.detail)|| (json&&json.message) || ("HTTP "+res.status)); return json.data; }
    async function parseLink(raw, source){ const url=extractDouyinUrl(raw); if(!url){setStatus(els.status,"没有识别到抖音链接。","err");return;} if(source!=="manual"&&url===state.lastUrl)return; state.lastUrl=url; els.input.value=raw; setStatus(els.status,"正在解析，请稍候..."); els.parseBtn.disabled=true; try{const data=await api("/api/v1/parse?url="+encodeURIComponent(url)); renderResult(data); setStatus(els.status,"解析成功，已生成预览和下载地址。","ok"); if(els.autoDownload.checked&&data.download&&data.download.download_url)triggerDownload(data.download.download_url,data.download.filename||"douyin-video.mp4");}catch(err){setStatus(els.status,err.message||String(err),"err");}finally{els.parseBtn.disabled=false;} }
    function renderResult(data){ const videoUrl=(data.download&&data.download.video_proxy_url)||(data.media&&data.media.video_url)||""; els.mediaType.textContent=data.media&&data.media.type==="video"?"视频":data.media&&data.media.type==="image"?"图文":"未知"; els.videoTitle.textContent=(data.content&&data.content.desc)||"未解析到标题"; els.videoAuthor.textContent=data.author&&data.author.nickname?"@"+data.author.nickname:"作者信息未解析"; els.desc.textContent=(data.content&&data.content.desc)||(data.author&&data.author.signature)||"--"; els.music.textContent=[data.music&&data.music.title,data.music&&data.music.author].filter(Boolean).join(" · ")||"--"; els.digg.textContent=fmt(data.stats&&data.stats.digg_count); els.comment.textContent=fmt(data.stats&&data.stats.comment_count); els.share.textContent=fmt(data.stats&&data.stats.share_count); els.collect.textContent=fmt(data.stats&&data.stats.collect_count); if(data.media&&data.media.cover_url){els.cover.src=data.media.cover_url;els.cover.classList.remove("hidden");els.video.poster=data.media.cover_url;}else{els.cover.classList.add("hidden");els.video.removeAttribute("poster");} if(videoUrl){els.video.src=videoUrl;els.video.load();els.video.play().catch(function(){});els.empty.classList.add("hidden");} const dl=(data.download&&data.download.download_url)||(data.media&&data.media.video_url)||""; els.downloadUrl.textContent=dl||"--"; els.downloadBtn.href=dl||"#"; els.downloadBtn.download=(data.download&&data.download.filename)||"douyin-video.mp4"; }
    function triggerDownload(url,filename){ if(!url||state.lastDownloaded===url)return; state.lastDownloaded=url; const a=document.createElement("a"); a.href=url; a.download=filename; a.style.display="none"; document.body.appendChild(a); a.click(); a.remove(); }
    els.parseBtn.addEventListener("click",function(){parseLink(els.input.value,"manual");}); els.clearBtn.addEventListener("click",function(){els.input.value="";state.lastUrl="";setStatus(els.status,"已清空，等待链接输入。");}); els.input.addEventListener("input",debounce(function(){ if(extractDouyinUrl(els.input.value))parseLink(els.input.value,"input"); },650)); document.addEventListener("paste",function(event){const text=(event.clipboardData&&event.clipboardData.getData("text"))||""; if(extractDouyinUrl(text)){els.input.value=text;setTimeout(function(){parseLink(text,"paste");},30);}}); els.clipboardBtn.addEventListener("click",async function(){state.clipboardWatch=true;els.clipboardBtn.textContent="剪贴板识别中";await scanClipboard();}); async function scanClipboard(){if(!state.clipboardWatch||!navigator.clipboard||!navigator.clipboard.readText)return;try{const text=await navigator.clipboard.readText();if(extractDouyinUrl(text)){els.input.value=text;await parseLink(text,"clipboard");}}catch{}} window.addEventListener("focus",scanClipboard); setInterval(scanClipboard,4500); async function pingOnline(){const client_id=localStorage.getItem("online_client_id")||(crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random());localStorage.setItem("online_client_id",client_id);try{const data=await api("/api/v1/online/ping",{method:"POST",body:JSON.stringify({client_id})});els.onlineCount.textContent=data.online_count;}catch{els.onlineCount.textContent="--";}} setInterval(pingOnline,15000); pingOnline();
    async function refreshVip(){try{const data=await api("/api/v1/vip/status"); els.vipState.textContent=data.activated?"已激活":"未激活"; els.vipState.className="pill"+(data.activated?" success":"");}catch{}} els.vipBtn.addEventListener("click",async function(){try{const data=await api("/api/v1/vip/activate",{method:"POST",body:JSON.stringify({code:els.vipCode.value})}); state.vipToken=data.token; localStorage.setItem("vip_token",data.token); els.vipState.textContent="已激活"; els.vipState.className="pill success"; setStatus(els.batchStatus,"会员已激活，可以批量解析。","ok");}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}}); refreshVip();
    els.inspectBtn.addEventListener("click",async function(){try{setStatus(els.batchStatus,"正在获取主页作品数量..."); const data=await api("/api/v1/batch/inspect",{method:"POST",body:JSON.stringify({url:els.profileInput.value})}); els.batchCount.max=data.available_count||data.total_count||999; setStatus(els.batchStatus,"检测到作品总数 "+(data.total_count??"未知")+"，当前可直接读取 "+data.available_count+" 个。","ok");}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}});
    els.startBatchBtn.addEventListener("click",async function(){try{setStatus(els.batchStatus,"正在创建批量任务..."); const task=await api("/api/v1/batch/start",{method:"POST",body:JSON.stringify({url:els.profileInput.value,count:Number(els.batchCount.value),concurrency:Number(els.batchConcurrency.value)})}); renderBatch(task); pollBatch(task.id);}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}});
    async function pollBatch(id){clearTimeout(state.pollTimer);try{const task=await api("/api/v1/batch/"+encodeURIComponent(id)); renderBatch(task); if(task.status==="queued"||task.status==="running")state.pollTimer=setTimeout(function(){pollBatch(id);},1500);}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}}
    function renderBatch(task){els.batchSummary.textContent=task.completed_count+"/"+task.requested_count; setStatus(els.batchStatus,"任务 "+task.status+"：成功 "+task.success_count+"，失败 "+task.failed_count+"。",task.status==="failed"?"err":"ok"); els.batchList.innerHTML=task.items.map(function(item){return '<div class="batch-item"><img class="thumb" src="'+esc(item.cover_url||"")+'" alt=""><div><b>'+esc(item.title||item.aweme_id)+'</b><div class="mono">'+esc(item.aweme_id)+'</div></div>'+(item.download_url?'<a class="pill success" href="'+esc(item.download_url)+'" download>下载</a>':'<span class="pill '+esc(item.status)+'">'+esc(item.status)+'</span>')+'</div>';}).join("")||'<p class="hint">暂无结果。</p>'; }
    function esc(v){return String(v||"").replace(/[&<>"']/g,function(m){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m];});}
  </script>
</body>
</html>`;
}
