const SITE_TITLE = "抖音视频解析";
const PRODUCT_NAME = "抖映灵感台";
const SITE_SUBTITLE = "粘贴分享链接，视频居中预览；解析、下载、主页采集、评论与口播文案都围绕当前视频展开";

export function renderHomePage(): string {
  return String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
  <meta name="theme-color" content="#030303" />
  <title>${SITE_TITLE} - ${PRODUCT_NAME}</title>
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <style>
    :root{color-scheme:dark;--bg:#030303;--panel:#111113;--panel2:#17171b;--line:rgba(255,255,255,.09);--text:#f7f7f8;--muted:rgba(255,255,255,.58);--cyan:#25f4ee;--pink:#fe2c55;--green:#63f59b;--orange:#ffd166;--radius:24px;--shadow:0 24px 70px rgba(0,0,0,.42)}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 28% 8%,rgba(37,244,238,.12),transparent 30%),radial-gradient(circle at 76% 4%,rgba(254,44,85,.14),transparent 34%),linear-gradient(180deg,#08080a,#030303 46%);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;color:var(--text);overflow-x:hidden}button,input,textarea{font:inherit}p{margin:0}a{color:inherit}
    .page{width:min(1220px,100%);margin:0 auto;padding:28px 18px 44px}.header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:18px}.brand{display:flex;gap:12px;align-items:center}.logo{width:46px;height:46px;border-radius:15px;background:linear-gradient(135deg,var(--cyan),var(--pink));display:grid;place-items:center;font-size:24px;font-weight:900;box-shadow:5px 0 0 rgba(254,44,85,.45),-5px 0 0 rgba(37,244,238,.36)}h1{margin:0;font-size:26px;letter-spacing:.02em}.subtitle{margin-top:5px;color:var(--muted);font-size:14px;line-height:1.5}.online{display:flex;align-items:center;gap:8px;border:1px solid var(--line);background:rgba(255,255,255,.06);border-radius:999px;color:#fff;padding:10px 14px;font-weight:800;white-space:nowrap}.online i{width:8px;height:8px;border-radius:99px;background:var(--green);box-shadow:0 0 16px var(--green)}
    .hero{display:grid;grid-template-columns:310px minmax(340px,460px) 360px;gap:18px;align-items:start}.card{background:linear-gradient(180deg,rgba(255,255,255,.07),rgba(255,255,255,.035));border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);backdrop-filter:blur(16px)}.pad{padding:18px}.card h2{font-size:16px;margin:0 0 13px}.eyebrow{display:inline-flex;align-items:center;gap:6px;border:1px solid rgba(37,244,238,.25);background:rgba(37,244,238,.08);border-radius:999px;color:var(--cyan);font-size:12px;font-weight:800;padding:5px 9px;margin-bottom:12px}.input{width:100%;min-height:126px;resize:vertical;border:1px solid var(--line);border-radius:18px;background:#070708;color:#fff;padding:15px;line-height:1.55;outline:0}.textarea-sm{min-height:92px}.input:focus,.small-input:focus{border-color:rgba(37,244,238,.75);box-shadow:0 0 0 4px rgba(37,244,238,.08)}.small-input{width:100%;height:44px;border:1px solid var(--line);border-radius:999px;background:#070708;color:#fff;padding:0 14px;outline:0}.btn{border:0;border-radius:999px;min-height:44px;padding:0 16px;background:rgba(255,255,255,.10);color:#fff;font-weight:850;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;gap:8px}.btn:hover{transform:translateY(-1px)}.btn:disabled{opacity:.45;cursor:not-allowed;transform:none}.btn-primary{background:linear-gradient(135deg,var(--cyan),var(--pink));color:#fff}.btn-wide{width:100%;margin-top:12px}.btn-row{display:flex;gap:10px;margin-top:10px}.btn-row .btn{flex:1}.toggle{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:13px;margin-top:12px}.toggle input{accent-color:var(--pink)}.status{min-height:21px;margin-top:12px;color:var(--muted);font-size:13px;line-height:1.55}.status.ok{color:var(--green)}.status.err{color:var(--pink)}
    .stage{display:grid;gap:14px}.phone-wrap{padding:10px;border-radius:34px;background:linear-gradient(135deg,rgba(37,244,238,.12),rgba(254,44,85,.12));border:1px solid var(--line);box-shadow:var(--shadow)}.phone{position:relative;aspect-ratio:9/16;border-radius:27px;overflow:hidden;background:#000;border:1px solid rgba(255,255,255,.10)}video{width:100%;height:100%;object-fit:contain;background:#000}.empty{position:absolute;inset:0;display:grid;place-items:center;text-align:center;padding:32px;background:radial-gradient(circle at 50% 24%,rgba(254,44,85,.12),transparent 40%),#050506}.empty.hidden{display:none}.empty strong{display:block;font-size:28px;text-shadow:4px 0 0 rgba(254,44,85,.50),-4px 0 0 rgba(37,244,238,.38);margin-bottom:10px}.empty span{display:block;color:var(--muted);line-height:1.65}.caption{background:rgba(17,17,19,.82);border:1px solid var(--line);border-radius:20px;padding:14px 16px;backdrop-filter:blur(12px);box-shadow:var(--shadow)}.video-title{font-weight:900;line-height:1.45}.video-author{font-size:13px;color:var(--muted);margin-top:6px}.quick{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.quick .mini{background:rgba(255,255,255,.06);border:1px solid var(--line);border-radius:16px;padding:10px;text-align:center}.mini b{display:block}.mini span{display:block;color:var(--muted);font-size:12px;margin-top:3px}
    .stats{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.stat{background:#08080a;border:1px solid var(--line);border-radius:16px;padding:13px}.stat b{font-size:18px}.stat span{display:block;color:var(--muted);font-size:12px;margin-top:4px}.meta{display:grid;gap:10px;margin-top:12px}.meta-item{background:#0b0b0d;border:1px solid var(--line);border-radius:16px;padding:12px}.meta-item small{display:block;color:var(--muted);margin-bottom:6px}.cover{width:100%;max-height:160px;object-fit:cover;border-radius:16px;border:1px solid var(--line)}.mono{font-family:Consolas,"SFMono-Regular",monospace;font-size:12px;word-break:break-all;color:rgba(255,255,255,.68);max-height:86px;overflow:auto}.pill{font-size:12px;border-radius:999px;padding:5px 9px;background:rgba(255,255,255,.08);color:var(--muted)}.pill.success{background:var(--green);color:#07120c}.hidden{display:none!important}
    details{margin-top:14px;border-top:1px solid var(--line);padding-top:14px}summary{cursor:pointer;color:#fff;font-weight:850}.hint{color:var(--muted);font-size:13px;line-height:1.6}.batch-grid{display:grid;gap:10px;margin-top:12px}.member-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.member-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.batch-row{display:grid;grid-template-columns:1fr 70px 70px;gap:8px}.batch-list{display:grid;gap:10px;max-height:300px;overflow:auto}.batch-item{display:grid;grid-template-columns:46px 1fr auto;gap:10px;align-items:center;background:#09090b;border:1px solid var(--line);border-radius:15px;padding:9px}.thumb{width:46px;height:60px;object-fit:cover;border-radius:10px;background:#111}.ai-output{white-space:pre-wrap;background:#08080a;border:1px solid var(--line);border-radius:16px;min-height:132px;max-height:310px;overflow:auto;padding:12px;color:#fff;line-height:1.65}.toolbar{display:grid;grid-template-columns:1fr 1fr;gap:8px}.workspace-name{color:var(--muted);font-size:12px;margin-top:4px}
    @media(max-width:1120px){.hero{grid-template-columns:1fr;max-width:560px;margin:0 auto}.header{align-items:flex-start;flex-direction:column}.phone{max-height:78vh}.stage{order:-1}}@media(max-width:720px){.page{padding:16px 12px 28px}.header{gap:12px;margin-bottom:14px}.logo{width:40px;height:40px;flex:0 0 auto;font-size:22px}h1{font-size:22px}.subtitle{font-size:12px}.online{width:100%;justify-content:center;padding:9px 11px}.hero{gap:13px}.card{border-radius:20px}.pad{padding:14px}.input{min-height:104px;border-radius:16px;font-size:14px}.btn{min-height:48px}.btn-row{display:grid;grid-template-columns:1fr 82px}.phone-wrap{padding:6px;border-radius:28px}.phone{border-radius:23px}.caption{padding:12px 13px;font-size:14px}.quick{grid-template-columns:repeat(3,1fr)}.stats{grid-template-columns:repeat(4,1fr);gap:6px}.stat{padding:10px 7px;border-radius:14px}.stat b{font-size:15px}.stat span{font-size:11px}.batch-row{grid-template-columns:1fr 64px 64px}}
  </style>
</head>
<body>
  <main class="page">
    <header class="header">
      <div class="brand"><div class="logo">♪</div><div><h1>${PRODUCT_NAME}</h1><p class="workspace-name">${SITE_TITLE}</p><p class="subtitle">${SITE_SUBTITLE}</p></div></div>
      <div class="online"><i></i><span>在线 <b id="onlineCount">--</b></span></div>
    </header>

    <section class="hero">
      <aside class="card pad">
        <span class="eyebrow">链接识别</span>
        <h2>粘贴视频或主页链接</h2>
        <textarea id="linkInput" class="input" placeholder="粘贴抖音分享文本 / 视频链接 / 主页链接，例如：https://v.douyin.com/xxxx/"></textarea>
        <button id="parseBtn" class="btn btn-primary btn-wide">解析并预览</button>
        <div class="btn-row"><button id="clipboardBtn" class="btn" type="button">剪贴板识别</button><button id="clearBtn" class="btn" type="button">清空</button></div>
        <label class="toggle"><input id="autoDownload" type="checkbox" checked /> 解析成功后自动下载视频</label>
        <div id="status" class="status">等待链接输入。</div>

        <details>
          <summary>会员权益 / 主页批量</summary>
          <div class="batch-grid">
            <p class="hint">激活码用于创建账号；登录后可使用主页预览、批量采集、评论导出、AI 口播文案和套餐队列权益。</p>
            <input id="vipCode" class="small-input" placeholder="激活码：PRO-2026-001" />
            <div class="member-row"><input id="memberUser" class="small-input" placeholder="账号（3-40位）" /><input id="memberPass" class="small-input" type="password" placeholder="密码（至少8位）" /></div>
            <div class="member-actions"><button id="vipBtn" class="btn btn-primary" type="button">激活并创建账号</button><button id="loginBtn" class="btn" type="button">账号登录</button></div>
            <span id="vipState" class="pill">未登录</span>
            <div id="memberBenefits" class="hint">会员权益会在登录后展示。</div>
            <input id="profileInput" class="small-input" placeholder="主页链接：https://www.douyin.com/user/..." />
            <div class="batch-row"><button id="inspectBtn" class="btn" type="button">获取上限</button><input id="batchCount" class="small-input" type="number" min="1" value="5" /><input id="batchConcurrency" class="small-input" type="number" min="1" max="5" value="3" /></div>
            <button id="startBatchBtn" class="btn btn-primary" type="button">创建采集任务</button>
            <div id="batchStatus" class="status">激活会员后可用。</div>
          </div>
        </details>
      </aside>

      <section class="stage">
        <div class="phone-wrap"><section class="phone"><video id="video" controls playsinline preload="metadata"></video><div id="empty" class="empty"><div><strong>视频在中心</strong><span>解析、预览、下载、评论、口播文案都围绕这条视频展开。</span></div></div></section></div>
        <div class="caption"><div id="videoTitle" class="video-title">还没有解析内容</div><div id="videoAuthor" class="video-author">标题、介绍、音乐和封面会自动展示</div></div>
        <div class="quick"><div class="mini"><b id="diggMini">--</b><span>点赞</span></div><div class="mini"><b id="commentMini">--</b><span>评论</span></div><div class="mini"><b id="shareMini">--</b><span>转发</span></div></div>
      </section>

      <aside class="card pad">
        <span class="eyebrow">AI 文案</span>
        <h2>口播文案与改写</h2>
        <textarea id="aiPrompt" class="input textarea-sm" placeholder="可选：输入你的改写要求，例如：改成小红书种草风格，口语化，结尾带引导。"></textarea>
        <div class="toolbar" style="margin-top:10px"><button id="aiScriptBtn" class="btn btn-primary" type="button">生成口播</button><button id="aiRewriteBtn" class="btn" type="button">按提示改写</button></div>
        <div id="aiStatus" class="status">会员登录后可调用大模型；未配置模型时会先用本地模板生成。</div>
        <div id="aiResult" class="ai-output">生成的视频口播文案、标题、介绍和标签会显示在这里。</div>
        <button id="copyAiBtn" class="btn btn-wide" type="button">复制文案</button>
        <details><summary>作品信息 / 下载</summary>
          <div class="stats" style="margin-top:12px"><div class="stat"><b id="digg">--</b><span>点赞</span></div><div class="stat"><b id="comment">--</b><span>评论</span></div><div class="stat"><b id="share">--</b><span>转发</span></div><div class="stat"><b id="collect">--</b><span>收藏</span></div></div>
          <div class="meta"><img id="cover" class="cover hidden" alt="视频封面" /><div class="meta-item"><small>标题 / 介绍</small><div id="desc">--</div></div><div class="meta-item"><small>背景音乐</small><div id="music">--</div></div><div class="meta-item"><small>下载地址</small><div id="downloadUrl" class="mono">--</div></div></div>
          <a id="downloadBtn" class="btn btn-primary btn-wide" href="#" download>下载视频</a>
        </details>
        <details><summary>批量结果</summary><div id="batchSummary" class="status">0/0</div><div class="toolbar" style="margin:10px 0"><button id="batchAiBtn" class="btn btn-primary" type="button">批量生成文案</button><button id="exportJsonBtn" class="btn" type="button">导出 JSON</button><button id="exportScriptsBtn" class="btn" type="button">导出文案</button><button id="exportCoversBtn" class="btn" type="button">导出封面</button><button id="exportCommentsBtn" class="btn" type="button">导出评论</button></div><div id="batchList" class="batch-list"><p class="hint">批量采集进度会显示在这里，支持导出视频、封面、评论、口播文案 JSON。</p></div></details>
      </aside>
    </section>
  </main>

  <script>
    const $ = (id) => document.getElementById(id);
    const state = { lastUrl: "", lastDownloaded: "", lastData: null, clipboardWatch: false, vipToken: localStorage.getItem("vip_token") || "", pollTimer: 0, lastBatchTaskId: localStorage.getItem("last_batch_task_id") || "" };
    const els = { input:$("linkInput"), parseBtn:$("parseBtn"), clipboardBtn:$("clipboardBtn"), clearBtn:$("clearBtn"), autoDownload:$("autoDownload"), status:$("status"), video:$("video"), empty:$("empty"), videoTitle:$("videoTitle"), videoAuthor:$("videoAuthor"), diggMini:$("diggMini"), commentMini:$("commentMini"), shareMini:$("shareMini"), digg:$("digg"), comment:$("comment"), share:$("share"), collect:$("collect"), desc:$("desc"), music:$("music"), cover:$("cover"), downloadUrl:$("downloadUrl"), downloadBtn:$("downloadBtn"), onlineCount:$("onlineCount"), vipCode:$("vipCode"), memberUser:$("memberUser"), memberPass:$("memberPass"), vipBtn:$("vipBtn"), loginBtn:$("loginBtn"), vipState:$("vipState"), memberBenefits:$("memberBenefits"), profileInput:$("profileInput"), inspectBtn:$("inspectBtn"), batchCount:$("batchCount"), batchConcurrency:$("batchConcurrency"), startBatchBtn:$("startBatchBtn"), batchAiBtn:$("batchAiBtn"), exportJsonBtn:$("exportJsonBtn"), exportScriptsBtn:$("exportScriptsBtn"), exportCoversBtn:$("exportCoversBtn"), exportCommentsBtn:$("exportCommentsBtn"), batchStatus:$("batchStatus"), batchList:$("batchList"), batchSummary:$("batchSummary"), aiPrompt:$("aiPrompt"), aiScriptBtn:$("aiScriptBtn"), aiRewriteBtn:$("aiRewriteBtn"), aiStatus:$("aiStatus"), aiResult:$("aiResult"), copyAiBtn:$("copyAiBtn") };
    function extractDouyinUrl(text){ const m=String(text||"").match(/https?:\/\/[^\s"'<>，。！？；、]+/i); if(!m)return""; try{const u=new URL(m[0]);const h=u.hostname.toLowerCase();return (h.endsWith("douyin.com")||h.endsWith("iesdouyin.com")||h.endsWith("amemv.com"))?u.toString():"";}catch{return"";} }
    function fmt(n){ return n===null||n===undefined?"--":Number(n).toLocaleString("zh-CN"); }
    function setStatus(el,msg,type){ el.textContent=msg; el.className="status"+(type?" "+type:""); }
    function debounce(fn,ms){ let t; return function(){ clearTimeout(t); const a=arguments; t=setTimeout(function(){ fn.apply(null,a); },ms); }; }
    async function api(path, options){ options=options||{}; const headers=new Headers(options.headers||{}); if(options.body&&!headers.has("content-type"))headers.set("content-type","application/json"); if(state.vipToken)headers.set("authorization","Bearer "+state.vipToken); const res=await fetch(path,Object.assign({},options,{headers})); const json=await res.json().catch(function(){return null;}); if(!res.ok||!json||json.ok===false)throw new Error((json&&json.error&&json.error.detail)|| (json&&json.message) || ("HTTP "+res.status)); return json.data; }
    async function parseLink(raw, source){ const url=extractDouyinUrl(raw); if(!url){setStatus(els.status,"没有识别到抖音链接。","err");return;} if(source!=="manual"&&url===state.lastUrl)return; state.lastUrl=url; els.input.value=raw; setStatus(els.status,"正在解析并生成视频预览..."); els.parseBtn.disabled=true; try{const data=await api("/api/v1/parse?url="+encodeURIComponent(url)); state.lastData=data; renderResult(data); setStatus(els.status,"解析成功，视频已居中预览。","ok"); if(els.autoDownload.checked&&data.download&&data.download.download_url)triggerDownload(data.download.download_url,data.download.filename||"douyin-video.mp4");}catch(err){setStatus(els.status,err.message||String(err),"err");}finally{els.parseBtn.disabled=false;} }
    function renderResult(data){ const videoUrl=(data.download&&data.download.video_proxy_url)||(data.media&&data.media.video_url)||""; els.videoTitle.textContent=(data.content&&data.content.desc)||"未解析到标题"; els.videoAuthor.textContent=data.author&&data.author.nickname?"@"+data.author.nickname:"作者信息未解析"; els.desc.textContent=(data.content&&data.content.desc)||(data.author&&data.author.signature)||"--"; els.music.textContent=[data.music&&data.music.title,data.music&&data.music.author].filter(Boolean).join(" · ")||"--"; els.digg.textContent=els.diggMini.textContent=fmt(data.stats&&data.stats.digg_count); els.comment.textContent=els.commentMini.textContent=fmt(data.stats&&data.stats.comment_count); els.share.textContent=els.shareMini.textContent=fmt(data.stats&&data.stats.share_count); els.collect.textContent=fmt(data.stats&&data.stats.collect_count); if(data.media&&data.media.cover_url){els.cover.src=data.media.cover_url;els.cover.classList.remove("hidden");els.video.poster=data.media.cover_url;}else{els.cover.classList.add("hidden");els.video.removeAttribute("poster");} if(videoUrl){els.video.src=videoUrl;els.video.load();els.video.play().catch(function(){});els.empty.classList.add("hidden");} const dl=(data.download&&data.download.download_url)||(data.media&&data.media.video_url)||""; els.downloadUrl.textContent=dl||"--"; els.downloadBtn.href=dl||"#"; els.downloadBtn.download=(data.download&&data.download.filename)||"douyin-video.mp4"; }
    function triggerDownload(url,filename){ if(!url||state.lastDownloaded===url)return; state.lastDownloaded=url; const a=document.createElement("a"); a.href=url; a.download=filename; a.style.display="none"; document.body.appendChild(a); a.click(); a.remove(); }
    async function runAi(mode){ if(!state.lastUrl){setStatus(els.aiStatus,"先解析一条视频，再生成口播文案。","err");return;} setStatus(els.aiStatus,"正在生成文案..."); try{const data=await api("/api/v1/ai/script",{method:"POST",body:JSON.stringify({url:state.lastUrl,prompt:els.aiPrompt.value,mode})}); els.aiResult.textContent=["标题："+data.title,"","口播文案：",data.rewritten_script,"","简介："+data.description,"标签："+(data.tags||[]).map(function(t){return "#"+t}).join(" "),"","来源："+data.provider].join("\n"); setStatus(els.aiStatus,"文案已生成。","ok");}catch(err){setStatus(els.aiStatus,err.message||String(err),"err");} }
    els.aiScriptBtn.addEventListener("click",function(){runAi("script")}); els.aiRewriteBtn.addEventListener("click",function(){runAi("custom_rewrite")}); els.copyAiBtn.addEventListener("click",async function(){try{await navigator.clipboard.writeText(els.aiResult.textContent||"");setStatus(els.aiStatus,"已复制文案。","ok");}catch{}});
    els.parseBtn.addEventListener("click",function(){parseLink(els.input.value,"manual");}); els.clearBtn.addEventListener("click",function(){els.input.value="";state.lastUrl="";state.lastData=null;setStatus(els.status,"已清空，等待链接输入。");}); els.input.addEventListener("input",debounce(function(){ if(extractDouyinUrl(els.input.value))parseLink(els.input.value,"input"); },650)); document.addEventListener("paste",function(event){const text=(event.clipboardData&&event.clipboardData.getData("text"))||""; if(extractDouyinUrl(text)){els.input.value=text;setTimeout(function(){parseLink(text,"paste");},30);}}); els.clipboardBtn.addEventListener("click",async function(){state.clipboardWatch=true;els.clipboardBtn.textContent="识别中";await scanClipboard();}); async function scanClipboard(){if(!state.clipboardWatch||!navigator.clipboard||!navigator.clipboard.readText)return;try{const text=await navigator.clipboard.readText();if(extractDouyinUrl(text)){els.input.value=text;await parseLink(text,"clipboard");}}catch{}} window.addEventListener("focus",scanClipboard); setInterval(scanClipboard,4500); async function pingOnline(){const client_id=localStorage.getItem("online_client_id")||(crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random());localStorage.setItem("online_client_id",client_id);try{const data=await api("/api/v1/online/ping",{method:"POST",body:JSON.stringify({client_id})});els.onlineCount.textContent=data.online_count;}catch{els.onlineCount.textContent="--";}} setInterval(pingOnline,15000); pingOnline();
    function renderMember(data){ const plan=data.member&&data.member.plan; els.vipState.textContent=data.activated?(data.member?("已登录 · "+data.member.username):"已激活"):"未登录"; els.vipState.className="pill"+(data.activated?" success":""); els.memberBenefits.textContent=plan?("套餐："+plan.name+" · 批量上限 "+plan.batch_parse_limit+" · AI "+plan.ai_daily_quota+"/日 · 并发 "+plan.concurrency+" · 优先级 "+plan.queue_priority):"会员权益会在登录后展示。"; if(plan){ els.batchCount.max=plan.batch_parse_limit; els.batchConcurrency.max=plan.concurrency; } }
    async function refreshVip(){try{renderMember(await api("/api/v1/me"));}catch{}}
    els.vipBtn.addEventListener("click",async function(){try{const data=await api("/api/v1/auth/register",{method:"POST",body:JSON.stringify({code:els.vipCode.value,username:els.memberUser.value,password:els.memberPass.value})}); state.vipToken=data.token; localStorage.setItem("vip_token",data.token); renderMember(data); setStatus(els.batchStatus,"账号已创建，批量与 AI 权益已启用。","ok");}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}});
    els.loginBtn.addEventListener("click",async function(){try{const data=await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify({username:els.memberUser.value,password:els.memberPass.value})}); state.vipToken=data.token; localStorage.setItem("vip_token",data.token); renderMember(data); setStatus(els.batchStatus,"登录成功，会员权益已同步。","ok");}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}});
    refreshVip();
    els.inspectBtn.addEventListener("click",async function(){try{setStatus(els.batchStatus,"正在获取主页作品上限..."); const data=await api("/api/v1/batch/inspect",{method:"POST",body:JSON.stringify({url:els.profileInput.value})}); els.batchCount.max=data.available_count||data.total_count||999; setStatus(els.batchStatus,"检测到作品总数 "+(data.total_count??"未知")+"，当前可读取 "+data.available_count+" 个。","ok");}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}});
    els.startBatchBtn.addEventListener("click",async function(){try{setStatus(els.batchStatus,"正在创建采集任务..."); const task=await api("/api/v1/batch/start",{method:"POST",body:JSON.stringify({url:els.profileInput.value,count:Number(els.batchCount.value),concurrency:Number(els.batchConcurrency.value)})}); state.lastBatchTaskId=task.id; localStorage.setItem("last_batch_task_id",task.id); renderBatch(task); pollBatch(task.id);}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}}); async function pollBatch(id){clearTimeout(state.pollTimer);try{const task=await api("/api/v1/batch/"+encodeURIComponent(id)); state.lastBatchTaskId=task.id; localStorage.setItem("last_batch_task_id",task.id); renderBatch(task); if(task.status==="queued"||task.status==="running")state.pollTimer=setTimeout(function(){pollBatch(id);},1500);}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}}
    async function runBatchAi(){ if(!state.lastBatchTaskId){setStatus(els.batchStatus,"先创建或恢复一个批量任务。","err");return;} try{setStatus(els.batchStatus,"正在批量生成口播文案..."); const data=await api("/api/v1/batch/"+encodeURIComponent(state.lastBatchTaskId)+"/ai",{method:"POST",body:JSON.stringify({prompt:els.aiPrompt.value,mode:"batch_script",count:Number(els.batchCount.value)||999})}); setStatus(els.batchStatus,"已生成 "+data.generated_count+" 条文案，可导出 JSON 或文案文本。","ok"); pollBatch(state.lastBatchTaskId);}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}}
    async function downloadExport(type){ if(!state.lastBatchTaskId){setStatus(els.batchStatus,"先创建或恢复一个批量任务。","err");return;} try{const headers=new Headers(); if(state.vipToken)headers.set("authorization","Bearer "+state.vipToken); const res=await fetch("/api/v1/batch/"+encodeURIComponent(state.lastBatchTaskId)+"/export?type="+encodeURIComponent(type),{headers}); if(!res.ok){const err=await res.json().catch(function(){return null;}); throw new Error((err&&err.error&&err.error.detail)||(err&&err.message)||("HTTP "+res.status));} const blob=await res.blob(); const cd=res.headers.get("content-disposition")||""; const m=cd.match(/filename="([^"]+)"/); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=m?m[1]:"batch-"+type+".json"; document.body.appendChild(a); a.click(); setTimeout(function(){URL.revokeObjectURL(a.href);a.remove();},1000); setStatus(els.batchStatus,"已开始导出 "+type+"。","ok");}catch(err){setStatus(els.batchStatus,err.message||String(err),"err");}}
    els.batchAiBtn.addEventListener("click",runBatchAi); els.exportJsonBtn.addEventListener("click",function(){downloadExport("json")}); els.exportScriptsBtn.addEventListener("click",function(){downloadExport("scripts")}); els.exportCoversBtn.addEventListener("click",function(){downloadExport("covers")}); els.exportCommentsBtn.addEventListener("click",function(){downloadExport("comments")});
    function renderBatch(task){els.batchSummary.textContent=task.completed_count+"/"+task.requested_count; setStatus(els.batchStatus,"任务 "+task.status+"：成功 "+task.success_count+"，失败 "+task.failed_count+"。",task.status==="failed"?"err":"ok"); els.batchList.innerHTML=task.items.map(function(item){return '<div class="batch-item"><img class="thumb" src="'+esc(item.cover_url||"")+'" alt=""><div><b>'+esc(item.title||item.aweme_id)+'</b><div class="mono">'+esc(item.aweme_id)+'</div></div>'+(item.download_url?'<a class="pill success" href="'+esc(item.download_url)+'" download>下载</a>':'<span class="pill '+esc(item.status)+'">'+esc(item.status)+'</span>')+'</div>';}).join("")||'<p class="hint">暂无结果。</p>'; }
    function esc(v){return String(v||"").replace(/[&<>"']/g,function(m){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m];});}
    if(state.lastBatchTaskId&&state.vipToken)pollBatch(state.lastBatchTaskId);
  </script>
</body>
</html>`;
}
